### PR TITLE
Mermaid diagram integration

### PR DESCRIPTION
**Pull request by mrmanc**
Hoping to include mermaid-js diagrams in slides.

- [x] Sizes are wrong for diagram unless you refresh page
- [x] Links in other content on the page are not clickable
- [x] Hide mermaid integration behind some configuration
- [x] Add docs to cover the configuration and syntax

### CODE REVIEW

**Comment by mrmanc** [comment]
The diagram sizes are wrong because the diagram is rendering while the slide is still animating as part of the transition. With a fade transition, it works. Adding approx 750ms delay also resolves the issue, although the content is missing for a while. In reveal.js v4.0.0 a `slidetransitioned` event appears, which would be a better mechanism than a simple delay. Alternatively, finding a way to change the transition for slides with diagrams on to something like fade. This is possible with reveal.js, but I’m not sure I’ll be able to do it by detecting that there is a diagram.

**Comment by mrmanc** [comment]
@dploeger any feelings about whether it feels appropriate to package and run the js to hook mermaid diagrams in without configuration?

**Comment by dploeger** [comment]
Sorry, you're way ahead of me with this now. 😅

Do you mean whether I find it okay to include mermaid directly into the distribution?

**Comment by dploeger** [comment]
I'd go with: Require a configuration to include mermaid. I'm also against adding things if they're not used.

**Comment by mrmanc** [comment]
Excellent. I was veering that way too. Will do. I’m closer to sorting the diagram sizes so this should be ready soon.

**Comment by mrmanc** [comment]
Okay, I think this looks good. Could you take a look and see if it works and you approve @dploeger?

**Review by dploeger — CHANGES_REQUESTED** [review]
Please remove the mermaid files from the repo as they're loaded from a cdn anyway.

**Comment by mrmanc** [comment]
Which files were you talking about?

I’ve only included a `mermaid.js` file adapted from https://github.com/ludwick/reveal.js-mermaid-plugin which is loaded from the local directory, and a new `mermaid.css` file to add some important style required for the diagrams. The actual mermaid files aren’t included in my changes—as you say they are loaded from their CDN.

Perhaps I could name the included JavaScript `reveal.js-mermaid-plugin.js` to make the distinction clearer?

**Comment by dploeger** [comment]
Ah okay, yes. That would be better because it confused me already. 😆

**Comment by mrmanc** [comment]
Okay, renamed and I’ve added some instructions and info about the feature toggle to the README and the new slide.

**Review by dploeger — APPROVED** [review]
Great addition. Thanks a lot. 🎁

**Comment by mrmanc** [comment]
Awesome. Just trying to work out whether I’ve done something wrong in the README before merging, as the mermaid code should render properly [here](https://github.com/dploeger/jekyll-revealjs/tree/mermaid-revealjs-plugin#user-content-svg-diagrams).

**Pull request merged**
